import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Footer from "@/components/Footer";
import Header from "@/components/Header";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
});

export const metadata: Metadata = {
  title: "Starknet",
  description: "Generated by create next app",
};

import { FiltersProvider } from "@/context/FiltersContext";

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} antialiased bg-body-background`}>
        <FiltersProvider>
          <Header />
          <main className="min-h-screen">{children}</main>
          <Footer />
        </FiltersProvider>
      </body>
    </html>
  );
}
