import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import Footer from "@/components/Footer";
import Header from "@/components/Header";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
});

export const metadata: Metadata = {
  title: "Starknet",
  description: "Generated by create next app",
};

import { FiltersProvider } from "@/context/FiltersContext";

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} antialiased bg-body-background`}> <script defer data-domain="sbtc-three.vercel.app" src="https://plausible.io/js/script.file-downloads.hash.outbound-links.pageview-props.revenue.tagged-events.js"></script>
<script>window.plausible = window.plausible || function() { (window.plausible.q = window.plausible.q || []).push(arguments) }</script>

        <FiltersProvider>
          <Header />
          <main className="min-h-screen">
            <div className="flex flex-col items-center p-4 text-secondary">
              <div className="text-center py-16 md:pt-24 text-white">
                <h1 className="text-4xl md:text-6xl font-semibold tracking-tight">
                  Find your Dream Job
                </h1>
                <p className="mt-2 text-base md:text-lg text-muted-foreground max-w-xl mx-auto">
                  Discover exciting job opportunities tailored to your skills for best results.
                </p>
              </div>
            </div>
            {children}
          </main>
          <Footer />
        </FiltersProvider>
      </body>
    </html>
  );
}
